RED_CIRCLE = "🔴"
BLUE_CIRCLE = "🔵"
WHITE_CIRCLE = "⚪"
BLACK_CIRCLE = "⚫"
GREEN_CIRCLE = "🟢"
PURPLE_CIRCLE = "🟣"
ORANGE_CIRCLE = "🟠"
YELLOW_CIRCLE = "🟡"

RED_HEART = "❤️"
BLUE_HEART = "💙"
WHITE_HEART = "🤍"
BLACK_HEART = "🖤"
GREEN_HEART = "💚"
PURPLE_HEART = "💜"
ORANGE_HEART = "🧡"
YELLOW_HEART = "💛"

LOUDSPEAKER = "📢"
FLAME = "🔥"
BOOK = "📙"
CLOCK = "⏰"
BELL = "🔔"
TWO = "2️"
THREE = "3️"
FOUR = "4️"
FIVE = "5️"
